[package]
name = "rust-tryout"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.11.0"
tokio = "1.0"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
env_logger = "0.9"

