[package]
name = "rust-tryout"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.11.0"
reqwest = { version = "0.11.3", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
tokio = "1.0"
tokio-macros = "1.0"

[[bin]]
name = "rust-tryout"
path = "main.rs"
